import CouncilPrompt from "./CouncilPrompt";
import TopBar from "./TopBar";
import ManagementPanels from "./ManagementPanels";
import DungeonPanel from "./DungeonPanel";
import CouncilScreen from "./CouncilScreen";

export default function GameView({ run, dungeon, raid, council, inventory, shell, actions }) {
  const { state, locked, isBuildPhase, isBattlePhase, contentWarnings } = run;
  const {
    core,
    activeEntrances,
    validation,
    roomsPlaced,
    coreMaxHp,
    dungeonLevel,
    maxRooms,
    heroesByTile,
    selectedTile,
    selectedHeroes,
    roomUpgradePrice,
    selectedMonsterRoomCapValue,
    canManageSelectedMonsterRoom,
    selectedMonsterRoomHasSpace,
    getTileGlyph,
    getTileRadarSpec,
    tileClass,
    roomTypeName,
    roomTypeDesc,
    roomTypeIcon,
    effectiveMonsterRoomCap,
    projectedTrapDamage,
    tileStateChip,
    tileHasAura,
    selectedTileAuras,
    atDungeonLevelCap,
    selectedIsAshBreach,
    selectedLinkInfo,
    selectedReadiness,
    selectedTileEffect,
    selectedLinkLabel,
    selectedLinkBonus,
    selectedTileFlags,
    selectedTrapSummary,
    dungeonRailStatus,
    dungeonRailSupport,
    checklist,
  } = dungeon;
  const {
    selectedHeroIntent,
    pendingRaidType,
    pendingEscalationLevel,
    pendingRaidOrder,
    pendingRaidLeaderTrait,
    pendingRaidCrestSrc,
    usePendingRaidCrest,
    pendingRaidMeta,
    pendingRaidDifficulty,
    pendingDirective,
    raidForecastMix,
    raidPlanReady,
    showInvasionChoiceCards,
    canStartRaid,
    canEndTurn,
  } = raid;
  const {
    councilSessionActive,
    showCouncilPrompt,
    councilAwaitingConclusion,
    councilRoster,
    focusedCouncilMember,
    absentCouncilMembers,
    focusedCouncilSponsor,
    focusedCouncilStanding,
    focusedCouncilCrestSrc,
    useFocusedCouncilCrest,
    useCouncilBackdrop,
    useCouncilSigil,
    useCouncilAbsentSilhouette,
    focusedCouncilBoons,
    councilQuestPlacementBlock,
    focusedCouncilSponsorStatus,
  } = council;
  const {
    artifactMods,
    ownedArtifactCounts,
    standardArtifactCollectedCount,
    standardArtifactAtCapCount,
    dealerCatalogExhausted,
    fusionPreview,
    ownedArtifactGroups,
    invPreview,
    evolutionButtonLabel,
    evolutionStageLabel,
  } = inventory;
  const {
    activeTab,
    sidePanel,
    mobileMenuOpen,
    councilScreenOpen,
    fuseA,
    fuseB,
    sacrificeIdx,
    selectedInventoryMonsterIndex,
    brokenTileArt,
    brokenCouncilArt,
    saveStatus,
    lastSavedAt,
    advancedToolboxOpen,
    onboardingComplete,
    onboardingStep,
    mobileTabs,
    activeMobileTab,
  } = shell;
  const {
    setSelected,
    clearTile,
    buildTrapRoom,
    buildMonsterRoom,
    buildUtilityRoom,
    armTrap,
    startMove,
    cancelMove,
    upgradeDungeon,
    upgradeDoctrine,
    upgradeRoom,
    selectTrapType,
    selectMonsterRoomType,
    selectUtilityRoomType,
  } = actions.dungeon;
  const {
    recruitMonster,
    startEvolution,
    chooseEvolution,
    cancelEvolution,
    placeInventoryMonsterInSelectedRoom,
    addMonsterToRoom,
    returnMonsterFromSelectedRoom,
    returnAllMonstersFromSelectedRoom,
  } = actions.monsters;
  const {
    buyArtifact,
    buyFromFleshMarket,
    buyFromTrader,
    sacrificeMonster,
    triggerFusion,
  } = actions.markets;
  const {
    activateDominionPower,
    selectInvasionChoice,
    beginBattle,
    startRaid,
    endTurn,
  } = actions.raid;
  const {
    attendCouncil,
    declineCouncil,
    concludeCouncil,
    acceptCouncilBoon,
    acceptCouncilQuest,
  } = actions.council;
  const { resetRun, newRun, dismissOnboarding } = actions.run;
  const {
    loadRun,
    saveRun,
    exportRun,
    importRun,
    restoreBackup,
    copyDiagnosticsBundle,
  } = actions.persistence;
  const {
    setActiveTab,
    setMobileMenuOpen,
    setCouncilScreenOpen,
    setFocusedCouncilKey,
    setFuseA,
    setFuseB,
    setSacrificeIdx,
    setSelectedInventoryMonsterIndex,
    setAdvancedToolboxOpen,
    noteBrokenTileArt,
    noteBrokenCouncilArt,
    selectMobileTab,
    closeShellDrawer,
  } = actions.shell;

  function drawerPanelTitle(label) {
    return (
      <div className="panelTitle">
        <span>{label}</span>
        <button className="drawerClose" type="button" onClick={closeShellDrawer}>
          Close
        </button>
      </div>
    );
  }

  return (
    <div className="app">
      <TopBar
        {...{
          activeMobileTab,
          activeTab,
          lastSavedAt,
          mobileMenuOpen,
          mobileTabs,
          saveStatus,
          selectMobileTab,
          setMobileMenuOpen,
          state,
        }}
      />

      {showCouncilPrompt && <CouncilPrompt {...{ attendCouncil, declineCouncil }} />}

      {councilScreenOpen && councilSessionActive && (
        <CouncilScreen
          {...{
            absentCouncilMembers,
            acceptCouncilBoon,
            acceptCouncilQuest,
            brokenCouncilArt,
            concludeCouncil,
            councilAwaitingConclusion,
            councilQuestPlacementBlock,
            councilRoster,
            focusedCouncilBoons,
            focusedCouncilCrestSrc,
            focusedCouncilMember,
            focusedCouncilSponsor,
            focusedCouncilSponsorStatus,
            focusedCouncilStanding,
            noteBrokenCouncilArt,
            setCouncilScreenOpen,
            setFocusedCouncilKey,
            state,
            useCouncilAbsentSilhouette,
            useCouncilBackdrop,
            useCouncilSigil,
            useFocusedCouncilCrest,
          }}
        />
      )}

      <div className="layout" data-tab={activeTab} data-side={sidePanel}>
        <DungeonPanel
          {...{
            atDungeonLevelCap,
            beginBattle,
            brokenTileArt,
            cancelMove,
            canEndTurn,
            canStartRaid,
            coreMaxHp,
            councilSessionActive,
            dismissOnboarding,
            dungeonLevel,
            dungeonRailStatus,
            dungeonRailSupport,
            endTurn,
            getTileGlyph,
            getTileRadarSpec,
            heroesByTile,
            isBattlePhase,
            isBuildPhase,
            locked,
            maxRooms,
            noteBrokenTileArt,
            onboardingComplete,
            onboardingStep,
            raidPlanReady,
            roomsPlaced,
            roomTypeIcon,
            roomTypeName,
            selectedHeroes,
            selectedLinkBonus,
            selectedLinkLabel,
            selectedReadiness,
            selectedTile,
            selectedTileAuras,
            selectedTileEffect,
            selectedTileFlags,
            selectedTrapSummary,
            selectMobileTab,
            setSelected,
            startMove,
            startRaid,
            state,
            tileClass,
            tileHasAura,
            tileStateChip,
            upgradeDungeon,
            validation,
          }}
        />

        <ManagementPanels
          {...{
            acceptCouncilBoon,
            acceptCouncilQuest,
            activateDominionPower,
            activeEntrances,
            addMonsterToRoom,
            advancedToolboxOpen,
            armTrap,
            artifactMods,
            attendCouncil,
            buildMonsterRoom,
            buildTrapRoom,
            buildUtilityRoom,
            buyArtifact,
            buyFromFleshMarket,
            buyFromTrader,
            cancelEvolution,
            canManageSelectedMonsterRoom,
            checklist,
            chooseEvolution,
            clearTile,
            concludeCouncil,
            contentWarnings,
            copyDiagnosticsBundle,
            core,
            councilAwaitingConclusion,
            councilQuestPlacementBlock,
            councilSessionActive,
            dealerCatalogExhausted,
            declineCouncil,
            drawerPanelTitle,
            effectiveMonsterRoomCap,
            evolutionButtonLabel,
            evolutionStageLabel,
            exportRun,
            focusedCouncilMember,
            focusedCouncilSponsor,
            focusedCouncilStanding,
            fuseA,
            fuseB,
            fusionPreview,
            importRun,
            invPreview,
            isBattlePhase,
            isBuildPhase,
            loadRun,
            locked,
            maxRooms,
            newRun,
            ownedArtifactCounts,
            ownedArtifactGroups,
            pendingDirective,
            pendingEscalationLevel,
            pendingRaidCrestSrc,
            pendingRaidDifficulty,
            pendingRaidLeaderTrait,
            pendingRaidMeta,
            pendingRaidOrder,
            pendingRaidType,
            placeInventoryMonsterInSelectedRoom,
            projectedTrapDamage,
            raidForecastMix,
            recruitMonster,
            resetRun,
            restoreBackup,
            returnAllMonstersFromSelectedRoom,
            returnMonsterFromSelectedRoom,
            roomsPlaced,
            roomTypeDesc,
            roomTypeIcon,
            roomTypeName,
            roomUpgradePrice,
            sacrificeIdx,
            sacrificeMonster,
            saveRun,
            saveStatus,
            selectInvasionChoice,
            selectMonsterRoomType,
            selectTrapType,
            selectUtilityRoomType,
            selectedHeroes,
            selectedHeroIntent,
            selectedInventoryMonsterIndex,
            selectedIsAshBreach,
            selectedLinkBonus,
            selectedLinkInfo,
            selectedMonsterRoomCapValue,
            selectedMonsterRoomHasSpace,
            selectedReadiness,
            selectedTile,
            selectedTileAuras,
            setActiveTab,
            setAdvancedToolboxOpen,
            setFocusedCouncilKey,
            setFuseA,
            setFuseB,
            setSacrificeIdx,
            setSelectedInventoryMonsterIndex,
            showInvasionChoiceCards,
            standardArtifactAtCapCount,
            standardArtifactCollectedCount,
            startEvolution,
            state,
            triggerFusion,
            upgradeDoctrine,
            upgradeRoom,
            usePendingRaidCrest,
            validation,
          }}
        />
      </div>
    </div>
  );
}
